### ISSUE TITLE
BUG: MultiWishlist Popup Overflow

### ISSUE THREAD

**Issue by gil--** [SnowdogApps/magento2-theme-blank-sass#125]
I discovered a bug with the multiple wishlist new popup but I can't find where in the Sass it's coming from. 

<img width="648" alt="screen shot 2017-01-06 at 3 48 19 pm" src="https://cloud.githubusercontent.com/assets/3484527/21732922/e81a6070-d429-11e6-9336-42294d518f37.png">

##### Styling
```css
.wishlist.window.popup {
    bottom: auto;
    top: 20%;
    left: 50%;
    margin-left: -212px;
    width: 380px;
    right: auto;
}
```

I was able to fix it in Chrome dev tools using the transform hack:

```css
.wishlist.window.popup {
    bottom: auto;
    top: 20%;
    left: 50%;
    width: 380px;
    right: auto;
    transform: translateX(-50%)
}
```

Basically, due to left: 50%, translateX will move the popup back to the center. I'm going to assume it won't work in all use-cases since left might not always be 50% if this is indeed a mixin generated CSS.

Sass map points to `Magento_Wishlist/styles/_module.scss` but I don't see it there. I'm assuming it's some mixin generating the styling but I can't find that either.
