### ISSUE TITLE
Regressions in 2.2 update

### ISSUE THREAD

**Issue by Leland** [SnowdogApps/magento2-theme-blank-sass#164]
Looks like #161 introduced some discrepancies. Chiefly, the removal of `!default` flags.

E.g https://github.com/SnowdogApps/magento2-theme-blank-sass/blob/34827e76e74ca12b21e510056d8e8da2b55cd563/Magento_Checkout/styles/module/checkout/_shipping.scss

https://github.com/SnowdogApps/magento2-theme-blank-sass/blob/34827e76e74ca12b21e510056d8e8da2b55cd563/Magento_Checkout/styles/module/checkout/_sidebar-shipping-information.scss

https://github.com/SnowdogApps/magento2-theme-blank-sass/blob/34827e76e74ca12b21e510056d8e8da2b55cd563/Magento_Checkout/styles/module/checkout/_tooltip.scss

...and many other files. Ideally, any variable definitions should end with a default flag.

Also, not sure about the usage of `lib-css` – it looks like that's used primarily to output vendor prefixed values and Frontools' autoprefixer takes care of that by default.

**Comment by Igloczek** [comment]
About the `!default` flags - you are right, feel free to submit PR or just wait a week or two for changes on our side.

About `lib-css` - no, is not related just to prefixes, it will let us to not add any properties, while variable have a `false` value. For more detail please check the source code.

**Comment by Leland** [comment]
> please don't complain about our work in that form, it's not nice for maintainers

Greatly appreciate the work you're doing here! Do apologize if there was a bad tone in my opened issue; can promise that there isn't one in my intent. I'm a contributor to this repository and may be able to fix this if you don't get to it first. Cheers.

**Comment by BenGlassAtlas** [comment]
I have noticed one issue where variables are set to `false` the word `false` is included in the CSS.

**Variable declaration**

```scss
File: vendor/snowdog/theme-blank-sass/Magento_Theme/styles/_module.scss:38

$footer__background-color                  : false;
```

**Usage**

```scss
File: vendor/snowdog/theme-blank-sass/Magento_Theme/styles/_module.scss:149

.page-footer {
    @include lib-css(background-color, $footer__background-color);
    margin-top: auto;
}
```

**Output**

```css
.page-footer {
  background-color: false;
  margin-top: auto; }
```
